services:
  - type: web
    name: techvaults-exam-system
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
    autoDeploy: true
